server:
  port: 8003
spring:
  cloud:
    gateway:
      routes:
        - id: operations-service
          uri: 'http://localhost:8002'
          predicates:
            - Path=/operations/**
        - id: account-service
          uri: 'http://localhost:8004'
          predicates:
            - Path=/accounts/**
        - id: user-service
          uri: 'http://localhost:8081'
          predicates:
            - Path=/user/**
  security:
    user:
      password: pas
      name: user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always

