server:
  port: 8004
spring:
  application:
    name: account-service
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always
