server:
  port: 8002
spring:
  application:
    name: operations-service
  datasource:
    url: jdbc:h2:mem:bankdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always